/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Table.java
 *
 * Created on Oct 22, 2010, 12:27:02 AM
 */

package RestOrdSystem;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author fff
 */
public class Table extends javax.swing.JFrame {

    /** Creates new form Table */
    public Table() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button18 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button13 = new javax.swing.JButton();
        Button14 = new javax.swing.JButton();
        Button15 = new javax.swing.JButton();
        Button17 = new javax.swing.JButton();
        Button12 = new javax.swing.JButton();
        Button11 = new javax.swing.JButton();
        Button16 = new javax.swing.JButton();
        Button16.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	}
        });
        Button19 = new javax.swing.JButton();
        Button20 = new javax.swing.JButton();
        Button10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 480));
        jPanel1.setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(371, 0, 40, 480);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table1.jpg")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 50, 71, 61);

        Button4.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table4.jpg")); // NOI18N
        Button4.setBorder(null);
        Button4.setBorderPainted(false);
        Button4.setContentAreaFilled(false);
        jPanel1.add(Button4);
        Button4.setBounds(680, 50, 71, 61);

        Button3.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table3.jpg")); // NOI18N
        Button3.setBorder(null);
        Button3.setBorderPainted(false);
        Button3.setContentAreaFilled(false);
        jPanel1.add(Button3);
        Button3.setBounds(580, 50, 71, 61);

        Button8.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table8.jpg")); // NOI18N
        Button8.setBorder(null);
        Button8.setBorderPainted(false);
        Button8.setContentAreaFilled(false);
        jPanel1.add(Button8);
        Button8.setBounds(730, 120, 71, 61);

        Button9.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table9.jpg")); // NOI18N
        Button9.setBorder(null);
        Button9.setBorderPainted(false);
        Button9.setContentAreaFilled(false);
        jPanel1.add(Button9);
        Button9.setBounds(390, 190, 71, 61);

        Button5.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table5.jpg")); // NOI18N
        Button5.setBorder(null);
        Button5.setBorderPainted(false);
        Button5.setContentAreaFilled(false);
        jPanel1.add(Button5);
        Button5.setBounds(420, 120, 71, 61);

        Button18.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table18.jpg")); // NOI18N
        Button18.setBorder(null);
        Button18.setBorderPainted(false);
        Button18.setContentAreaFilled(false);
        jPanel1.add(Button18);
        Button18.setBounds(490, 340, 71, 61);

        Button2.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table2.jpg")); // NOI18N
        Button2.setBorder(null);
        Button2.setBorderPainted(false);
        Button2.setContentAreaFilled(false);
        jPanel1.add(Button2);
        Button2.setBounds(490, 50, 71, 61);

        Button6.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table6.jpg")); // NOI18N
        Button6.setBorder(null);
        Button6.setBorderPainted(false);
        Button6.setContentAreaFilled(false);
        jPanel1.add(Button6);
        Button6.setBounds(540, 120, 71, 61);

        Button7.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table7.jpg")); // NOI18N
        Button7.setBorder(null);
        Button7.setBorderPainted(false);
        Button7.setContentAreaFilled(false);
        jPanel1.add(Button7);
        Button7.setBounds(640, 120, 71, 61);

        Button13.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table13.jpg")); // NOI18N
        Button13.setBorder(null);
        Button13.setBorderPainted(false);
        Button13.setContentAreaFilled(false);
        jPanel1.add(Button13);
        Button13.setBounds(420, 260, 71, 61);

        Button14.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table14.jpg")); // NOI18N
        Button14.setBorder(null);
        Button14.setBorderPainted(false);
        Button14.setContentAreaFilled(false);
        jPanel1.add(Button14);
        Button14.setBounds(540, 260, 71, 61);

        Button15.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table15.jpg")); // NOI18N
        Button15.setBorder(null);
        Button15.setBorderPainted(false);
        Button15.setContentAreaFilled(false);
        jPanel1.add(Button15);
        Button15.setBounds(640, 260, 71, 61);

        Button17.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table17.jpg")); // NOI18N
        Button17.setBorder(null);
        Button17.setBorderPainted(false);
        Button17.setContentAreaFilled(false);
        jPanel1.add(Button17);
        Button17.setBounds(390, 340, 71, 61);

        Button12.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table12.jpg")); // NOI18N
        Button12.setBorder(null);
        Button12.setBorderPainted(false);
        Button12.setContentAreaFilled(false);
        jPanel1.add(Button12);
        Button12.setBounds(680, 190, 71, 61);

        Button11.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table11.jpg")); // NOI18N
        Button11.setBorder(null);
        Button11.setBorderPainted(false);
        Button11.setContentAreaFilled(false);
        jPanel1.add(Button11);
        Button11.setBounds(580, 190, 71, 61);

        Button16.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table16.jpg")); // NOI18N
        Button16.setBorder(null);
        Button16.setBorderPainted(false);
        Button16.setContentAreaFilled(false);
        jPanel1.add(Button16);
        Button16.setBounds(730, 260, 71, 61);

        Button19.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table19.jpg")); // NOI18N
        Button19.setBorder(null);
        Button19.setBorderPainted(false);
        Button19.setContentAreaFilled(false);
        jPanel1.add(Button19);
        Button19.setBounds(590, 340, 71, 61);

        Button20.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table20.jpg")); // NOI18N
        Button20.setBorder(null);
        Button20.setBorderPainted(false);
        Button20.setContentAreaFilled(false);
        Button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(Button20);
        Button20.setBounds(690, 340, 71, 61);

        Button10.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\table10.jpg")); // NOI18N
        Button10.setBorder(null);
        Button10.setBorderPainted(false);
        Button10.setContentAreaFilled(false);
        jPanel1.add(Button10);
        Button10.setBounds(480, 190, 71, 61);

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("                 Please select your table");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 10, 450, 30);

        jLabel2.setText("Promotion");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 130, 260, 200);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("            FOOD RESTAURENT");
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 10, 370, 30);

        jButton21.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\OK.jpg")); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(490, 420, 70, 40);

        jButton22.setIcon(new javax.swing.ImageIcon("C:\\Users\\fff\\Desktop\\New Folder\\cancel.jpg")); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(600, 420, 70, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button13;
    private javax.swing.JButton Button14;
    private javax.swing.JButton Button15;
    private javax.swing.JButton Button17;
    private javax.swing.JButton Button12;
    private javax.swing.JButton Button11;
    private javax.swing.JButton Button16;
    private javax.swing.JButton Button19;
    private javax.swing.JButton Button20;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button10;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button18;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration

}
